jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Compile TypeScript
        run: npm run build # Ensure your package.json has "build": "tsc"
